source:
  copy_from:
    - ".publish/README.md"
    - ".gitattributes"
    - ".gitignore"
    - "common"
    - "project_A/pub"
    - "project_B/pub"
    - "project_C/pub/README.md"
    
target:
  repo: "target-owner/target-repo"  ## MODIFY
  maxsize_commit_MB: 1000
  commit_message: "just publishing"
  copy_to:
    - "README.md"
    - ".gitattributes"
    - ".gitignore"
    - "common"
    - "project_A"
    - "project_B"
    - "project_C/README.md"
  remove_after_copy:
