name: Repo Selective Sync

on: workflow_dispatch

jobs:

publish_to_repo:
  - name: "Publish to Target Repo"
    runs-on: ubuntu-latest
    steps:
      - uses: icub-tech-iit/gh-action-repo-selective-sync@v1.0.0
        with:
          recipe-file: '.resources/recipe.yml'
          token-source: ${{ secrets.GITHUB_TOKEN }}
          token-target: ${{ secrets.TARGET_PAT }}
